const db = {
  A: {mRNA: ['U'], DNA:['T'], full:["Adenine"] },
  C: {mRNA: ['G'], DNA:['G'], full:["Cytosine"] },
  T: {mRNA: ['A'], DNA:['A'], full:["Thymine"] },
  G: {mRNA: ['C'], DNA:['C'], full:["Guanine"] },  

 TTT: {mRNA: ['AAA'], DNA:['AAA'], full:["Lysine/Lys"] },  
 TTC: {mRNA: ['AAG'], DNA:['AAG'], full:["Lysine/Lys"] }, 
 TTA: {mRNA: ['AAU'], DNA:['AAA'], full:["Asparagine/Asn"] }, 
 TTG: {mRNA: ['AAC'], DNA:['AAC'], full:["Asparagine/Asn"] }, 
 TCT: {mRNA: ['AGA'], DNA:['AGA'], full:["Arginine/Arg"] }, 
 TCC: {mRNA: ['AGG'], DNA:['AGG'], full:["Arginine/Arg"] }, 
 TCA: {mRNA: ['AGU'], DNA:['AGT'], full:["Serine/Ser"] }, 
 TCG: {mRNA: ['AGC'], DNA:['AGC'], full:["Serine/Ser"] }, 
 TAT: {mRNA: ['AUA'], DNA:['ATA'], full:["Isoleucine/Ile"] }, 
 TAC: {mRNA: ['AUG'], DNA:['ATG'], full:["Methionine/Met (start)"] }, 
 TAA: {mRNA: ['AUU'], DNA:['ATT'], full:["Isoleucine/Ile"] }, 
 TAG: {mRNA: ['AUC'], DNA:['ATC'], full:["Isoleucine/Ile"] }, 
 TGT: {mRNA: ['ACA'], DNA:['ACA'], full:["Threonine/Thr"] }, 
 TGC: {mRNA: ['ACG'], DNA:['ACG'], full:["Threonine/Thr"] }, 
 TGA: {mRNA: ['ACU'], DNA:['ACT'], full:["Threonine/Thr"] }, 
 TGG: {mRNA: ['ACC'], DNA:['ACC'], full:["Threonine/Thr"] }, 
  
 CTT: {mRNA: ['GAA'], DNA:['GAA'], full:["Glutamic Acid/Glu"] }, 
 CTC: {mRNA: ['GAG'], DNA:['GAG'], full:["Glutamic Acid/Glu"] }, 
 CTA: {mRNA: ['GAU'], DNA:['GAT'], full:["Aspartic Acid/Asp"] }, 
 CTG: {mRNA: ['GAC'], DNA:['GAC'], full:["Aspartic Acid/Asp"] }, 
 CCT: {mRNA: ['GGA'], DNA:['GGA'], full:["Glycine/Gly"] }, 
 CCC: {mRNA: ['GGG'], DNA:['GGG'], full:["Glycine/Gly"] }, 
 CCA: {mRNA: ['GGU'], DNA:['GGT'], full:["Glycine/Gly"] }, 
 CCG: {mRNA: ['GGC'], DNA:['GGC'], full:["Glycine/Gly"] }, 
 CAT: {mRNA: ['GUA'], DNA:['AAA'], full:["Valine/Val"] }, 
 CAC: {mRNA: ['GUG'], DNA:['AAA'], full:["Valine/Val"] }, 
 CAA: {mRNA: ['GUU'], DNA:['GTT'], full:["Valine/Val"] }, 
 CAG: {mRNA: ['GUC'], DNA:['GTC'], full:["Valine/Val"] }, 
 CGT: {mRNA: ['GCA'], DNA:['GCA'], full:["Alanine/Ala"] }, 
 CGA: {mRNA: ['GCU'], DNA:['GCT'], full:["Alanine/Ala"] }, 
 CGC: {mRNA: ['GCG'], DNA:['GCG'], full:["Alanine/Ala"] }, 
 CGG: {mRNA: ['GCC'], DNA:['GCC'], full:["Alanine/Ala"] }, 
  
 ATT: {mRNA: ['UAA'], DNA:['TAA'], full:["Stop"] }, 
 ATC: {mRNA: ['UAG'], DNA:['TAG'], full:["Stop"] }, 
 ATA: {mRNA: ['UAU'], DNA:['TAT'], full:["Tyrosine/Tyr"] }, 
 ATG: {mRNA: ['UAC'], DNA:['TAC'], full:["Tyrosine/Tyr"] }, 
 ACT: {mRNA: ['UGA'], DNA:['TGA'], full:["Stop"] }, 
 ACC: {mRNA: ['UGG'], DNA:['TGG'], full:["Tryptophan/Trp"] }, 
 ACA: {mRNA: ['UGU'], DNA:['TGT'], full:["Cysteine/Cys"] }, 
 ACG: {mRNA: ['UGC'], DNA:['TGC'], full:["Cysteine/Cys"] }, 
 AAT: {mRNA: ['UUA'], DNA:['TTA'], full:["Leucine/Leu"] }, 
 AAC: {mRNA: ['UUG'], DNA:['TTG'], full:["Leucine/Leu"] }, 
 AAA: {mRNA: ['UUU'], DNA:['TTT'], full:["Phenylalanine/Phe"] }, 
 AAG: {mRNA: ['UUC'], DNA:['TTC'], full:["Phenylalanine/Phe"] }, 
 AGT: {mRNA: ['UCA'], DNA:['TCA'], full:["Serine/Ser"] }, 
 AGC: {mRNA: ['UCG'], DNA:['TCG'], full:["Serine/Ser"] }, 
 AGA: {mRNA: ['UCU'], DNA:['TCT'], full:["Serine/Ser"] }, 
 AGG: {mRNA: ['UCC'], DNA:['TCC'], full:["Serine/Ser"] }, 
 
 GTT: {mRNA: ['CAA'], DNA:['CAA'], full:["Glutamine/Gln"] }, 
 GTC: {mRNA: ['CAG'], DNA:['CAG'], full:["Glutamine/Gln"] }, 
 GTA: {mRNA: ['CAU'], DNA:['CAT'], full:["Histidine/His"] }, 
 GTG: {mRNA: ['CAC'], DNA:['CAC'], full:["Histidine/His"] }, 
 GCT: {mRNA: ['CGA'], DNA:['CGA'], full:["Arginine/Arg"] }, 
 GCC: {mRNA: ['CGG'], DNA:['CGG'], full:["Arginine/Arg"] }, 
 GCA: {mRNA: ['CGU'], DNA:['CGT'], full:["Arginine/Arg"] }, 
 GCG: {mRNA: ['CGC'], DNA:['CGC'], full:["Arginine/Arg"] }, 
 GAT: {mRNA: ['CUA'], DNA:['CTA'], full:["Leucine/Leu"] }, 
 GAC: {mRNA: ['CUG'], DNA:['CTG'], full:["Leucine/Leu"] }, 
 GAA: {mRNA: ['CUU'], DNA:['CTT'], full:["Leucine/Leu"] }, 
 GAG: {mRNA: ['CUC'], DNA:['CTC'], full:["Leucine/Leu"] }, 
 GGT: {mRNA: ['CCA'], DNA:['CCA'], full:["Proline/Pro"] }, 
 GGC: {mRNA: ['CCG'], DNA:['CCG'], full:["Proline/Pro"] }, 
 GGA: {mRNA: ['CCU'], DNA:['CCT'], full:["Proline/Pro"] }, 
 GGG: {mRNA: ['CCC'], DNA:['CCC'], full:["Proline/Pro"] }, 
 

};

export default db;